baseurl: ""
url: ""

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge

plugins:
  - jekyll-org

org:
  liquid: true
# sass:
#   sass_dir: _scss
#   style: :compressed
